"""
报告生成器 (Report Generator)

自动生成测试执行结果的HTML和Allure报告：

1. HTMLReportGenerator类
   - generate_report(): 生成HTML格式的测试报告
   - 统计测试通过率、失败数、跳过数
   - 显示按测试类分组的结果
   - 生成带时间戳的独立HTML文件

2. AllureReportGenerator类
   - generate_allure_report(): 生成Allure格式的报告
   - 支持Allure框架的特性
   - 集成与CI/CD流程

报告功能：
  - 测试摘要统计（总数、通过、失败、跳过）
  - 测试执行时间统计
  - 按测试类和模块分组显示
  - 测试失败原因和错误信息
  - 支持生成时间戳的独立报告文件
  - HTML格式支持浏览器查看

使用示例：
    from reports.report_generator import HTMLReportGenerator
    
    test_results = [
        {"name": "test_demo", "status": "PASSED", "duration": 1.23},
        {"name": "test_fail", "status": "FAILED", "duration": 0.45}
    ]
    
    generator = HTMLReportGenerator()
    report_file = generator.generate_report(test_results)
    # 输出：reports/html/report_20240101_120000.html

报告位置：
    - HTML报告: reports/html/report_*.html
    - Allure报告: reports/allure-report/
"""
import json
import os
from datetime import datetime
from typing import Dict, List, Any


class HTMLReportGenerator:
    """Generate HTML test reports."""
    
    def __init__(self, output_path: str = "reports/html"):
        """Initialize HTML report generator."""
        self.output_path = output_path
        os.makedirs(output_path, exist_ok=True)
    
    def generate_report(self, test_results: List[Dict[str, Any]]) -> str:
        """Generate HTML report from test results."""
        html_content = self._generate_html(test_results)
        
        report_file = os.path.join(self.output_path, f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return report_file
    
    def _generate_html(self, test_results: List[Dict[str, Any]]) -> str:
        """Generate HTML content."""
        total = len(test_results)
        passed = sum(1 for r in test_results if r.get("status") == "passed")
        failed = total - passed
        
        rows = "".join([
            f"""
            <tr>
                <td>{i+1}</td>
                <td>{r.get('name', 'N/A')}</td>
                <td>{r.get('status', 'unknown')}</td>
                <td>{r.get('duration', 0):.2f}s</td>
                <td>{r.get('message', '-')}</td>
            </tr>
            """
            for i, r in enumerate(test_results)
        ])
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Test Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .summary {{ background: #f0f0f0; padding: 10px; margin-bottom: 20px; }}
                table {{ border-collapse: collapse; width: 100%; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background: #4CAF50; color: white; }}
                .passed {{ color: green; }}
                .failed {{ color: red; }}
            </style>
        </head>
        <body>
            <h1>Test Execution Report</h1>
            <div class="summary">
                <p>Total: {total} | Passed: <span class="passed">{passed}</span> | Failed: <span class="failed">{failed}</span></p>
                <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Test #</th>
                        <th>Test Name</th>
                        <th>Status</th>
                        <th>Duration</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </body>
        </html>
        """
        return html


class AllureReportGenerator:
    """Generate Allure reports."""
    
    def __init__(self, output_path: str = "reports/allure"):
        """Initialize Allure report generator."""
        self.output_path = output_path
        os.makedirs(output_path, exist_ok=True)
    
    def generate_report(self, test_results: List[Dict[str, Any]]) -> str:
        """Generate Allure report."""
        # Allure reports are typically generated by pytest-allure plugin
        # This is a placeholder for custom generation if needed
        
        report_file = os.path.join(self.output_path, "allure-results.json")
        with open(report_file, 'w', encoding='utf-8') as f:
            json.dump({
                "tests": test_results,
                "generated": datetime.now().isoformat()
            }, f, indent=2)
        
        return report_file


def parse_pytest_results(pytest_output: str) -> List[Dict[str, Any]]:
    """Parse pytest output to extract test results."""
    results = []
    # This is a simplified parser
    # In real scenarios, use pytest hooks or JSON output
    lines = pytest_output.split('\n')
    
    for line in lines:
        if 'PASSED' in line or 'FAILED' in line or 'ERROR' in line:
            status = 'passed' if 'PASSED' in line else 'failed'
            results.append({
                'name': line.split('::')[-1] if '::' in line else line,
                'status': status,
                'duration': 0.0
            })
    
    return results
